sudo: false

branches:
  only:
  - gh-pages
  - /.*/
  - 
# Set the build language to Python
language: python

# Set the python version to 2.7
python: 3.6

# Install the codecov pip dependency
install:
  - python3 setup.py install

# Run the unit test
script:
  - coverage run setup.py test

# Push the results back to codecov
after_success:
  - coveralls